---
title: "p8105_hw3_hs3239"
author: "hanfu shi"
date: "2021/10/14"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(p8105.datasets)
data("instacart")

```

#Setting
```{r}
library(tidyverse)
library(readxl)
library(devtools)
library(dplyr)
library(ggplot2)
library(patchwork)
library(ggridges)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = 0.6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Problem 1
```{r}
#find the distinct id numbers
instacart_aisles = select(instacart, order_number,aisle_id)
id_number= count(instacart_aisles,aisle_id)



```
The dataset contains`r nrow(instacart)` rows and `r ncol(instacart)` columns(variables)
The key variables are Aisles, Aisles's ID and order ID. There are`r nrow(id_number)` aisles and fresh vegetables are the most item ordered.


```{r}
#P1 plot
instacart %>% 
  count(aisle) %>% 
  filter(n > 10000) %>% 
  mutate(
    aisle = factor(aisle),
    aisle = fct_reorder(aisle, n)
  ) %>% 
  ggplot(aes(x = aisle, y = n)) +
  geom_point()+
theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
  labs(title = "Aisle plot",
       x =  "Different Aisles",
       y = "Number of order",
       caption = "Data from instacart datasets")
```


```{r}
#p1 table1
instacart %>% 
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>% 
  group_by(aisle) %>% 
  count(product_name) %>% 
  mutate(rank = min_rank(desc(n))) %>% 
  filter(rank <=3) %>% 
  arrange(aisle, rank) %>% 
  knitr::kable()
```


```{r}
#p1 table2
instacart %>% 
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>% 
  group_by(product_name, order_dow) %>% 
  summarise(mean_hour = mean(order_hour_of_day)) %>% 
  pivot_wider(
    names_from = order_dow,
    values_from = mean_hour
  )%>%
  knitr::kable()

```



```{r}

```



```{r}

```